spring.profiles.active=${PROFILE_ACTIVE:prod}
server.port=4289
springdoc.swagger-ui.path=/swagger-ui-custom.html
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true

logging.level.org.hibernate.SQL=DEBUG
