
base_url:auto/prod/api/v1
server.servlet.context-path=/auto/prod/api/v1
springdoc.swagger-ui.path=/swagger-ui-custom.html

#Auto Gennerate SQL
spring.aop.auto=true
spring.jpa.show-sql=false
spring.auto.debit.primary.driver-class-name=oracle.jdbc.OracleDriver
spring.auto.debit.primary.jdbc-url=jdbc:oracle:thin:@//mbdb-dc-scan.ldblao.la:8129/MBPRODSVC
spring.auto.debit.primary.username=AUTO_DEBIT_USER
spring.auto.debit.primary.password=ldb@2026!
spring.auto.debit.primary.maximumPoolSize=20
spring.auto.debit.primary.connectionTimeout=3600000
spring.auto.debit.primary.idleTimeout=600000
spring.auto.debit.primary.minimumIdle=5
spring.auto.debit.primary.test-on-borrow=true
spring.auto.debit.primary.test-while-idle=true
spring.auto.debit.primary.time-between-eviction-runs-millis=3600000
spring.auto.debit.primary.jpa.show-sql=true
spring.auto.debit.primary.jpa.hibernate.ddl-auto=update
spring.auto.debit.primary.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
