spring.profiles.active=${PROFILE_ACTIVE:dev}
server.port=4289
springdoc.swagger-ui.path=/swagger-ui-custom.html
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force-response=true

# Batch and T24 settings
batch.key=
# if true, BatchService will mock closing balance as 1000. Set to false and provide t24.url to call real service
t24.mock=true
t24.url=

# Scheduled batch runner
batch.auto-run=true
batch.interval.ms=1800000
batch.initial.delay.ms=60000

logging.level.org.hibernate.SQL=DEBUG
