#
#base_url:auto/prod/api/v1
#server.servlet.context-path=/auto/prod/api/v1
#springdoc.swagger-ui.path=/swagger-ui-custom.html
#
##Auto Gennerate SQL
#spring.aop.auto=true
#spring.jpa.show-sql=false
#spring.auto.debit.primary.driver-class-name=oracle.jdbc.OracleDriver
#spring.auto.debit.primary.jdbc-url=${DEBIT_DB_URL:jdbc:oracle:jdbc:oracle:thin:@//mbdb-dc-scan.ldblao.la:8129/MBPRODSVC}
#spring.auto.debit.primary.username=${DEBIT_DB_USER:AUTO_DEBIT_USER}
#spring.auto.debit.primary.password=${DEBIT_DB_PASSWORD:ldb@2026!}
#spring.auto.debit.primary.maximumPoolSize=20
#spring.auto.debit.primary.connectionTimeout=3600000
#spring.auto.debit.primary.idleTimeout=600000
#spring.auto.debit.primary.minimumIdle=5
#spring.auto.debit.primary.test-on-borrow=true
#spring.auto.debit.primary.test-while-idle=true
#spring.auto.debit.primary.time-between-eviction-runs-millis=3600000
#spring.auto.debit.primary.jpa.show-sql=true
#spring.auto.debit.primary.jpa.hibernate.ddl-auto=update
#spring.auto.debit.primary.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
#
#spring.auto.t24.second.driver-class-name=oracle.jdbc.OracleDriver
#spring.auto.t24.second.jdbc-url=${COREBANK_DB_URL:jdbc:oracle:thin:@//cbsdb-dc-scan.ldblao.la:9849/CBSPRODSVC}
#spring.auto.t24.second.username=${COREBANK_DB_USER:MOBILE}
#spring.auto.t24.second.password=${COREBANK_DB_PASSWORD:Oracle#@!T24mobile842}
#spring.auto.t24.second.maximumPoolSize=20
#spring.auto.t24.second.connectionTimeout=3600000
#spring.auto.t24.second.idleTimeout=600000
#spring.auto.t24.second.minimumIdle=5
#spring.auto.t24.second.test-on-borrow=true
#spring.auto.t24.second.test-while-idle=true
#spring.auto.t24.second.time-between-eviction-runs-millis=3600000
#spring.auto.t24.second.jpa.show-sql=true
#spring.auto.t24.second.jpa.hibernate.ddl-auto=update
#spring.auto.t24.second.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
#
#
#TO_SERVICE_INTERVAL=3000
##==================== Corebanking UAT ================================================
#corebanking.connectionTimeout=${COREBANKING_CONNECT_TIMEOUT:60000}
#corebanking.readTimeout=${COREBANKING_READ_TIMEOUT:60000}
#corebanking.domain=${COREBANKING_DOMAIN:https://vboxz-cluster.ldblao.la}
#corebanking.baseUrl=${COREBANKING_BASEURL:https://vboxz-cluster.ldblao.la/t24-gateway/api/v1/trust}
#corebanking.fundTransfer=${COREBANKING_FUND_TRANSFER:/mobileFundTransfer.service}
#corebanking.reversal=${COREBANKING_FUND_TRANSFER:/reverseFundTransfer.service.mobile}
#
#
#media.upload.path=/var/www/html/mobile/QR/IMGMOBILE/loanImage/uploads/
#media.upload.url=https://dehome.ldblao.la/mobile/QR/IMGMOBILE/loanImage/uploads/
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB
